openapi: 3.0.1
info:
  title: Сервис контроля за стажировками
  version: v1

servers:
  - url: https://internship.staziss-tech.ru
    description: Основной сервер
tags:
  - name: logs
    description: Работа с логами стажировок
  - name: tags
    description: Работа с тегами
  - name: profile
    description: Работа с профилем пользователя
  - name: notifications
    description: Работа с уведомлениями

components:
  securitySchemes:
    openIdConnect:
      type: openIdConnect
      openIdConnectUrl: https://auth.staziss-tech.ru/realms/internship/.well-known/openid-configuration


paths:
  /logs/me:
    $ref: './schemas/logs/GetMyLogsApi.yaml'
  /logs/{userId}:
    $ref: './schemas/logs/GetUserLogsApi.yaml'
  /logs:
    $ref: './schemas/logs/CreateLogApi.yaml'
  /logs/{logId}:
    $ref: './schemas/logs/EditLogApi.yaml'

  /tags:
    $ref: './schemas/tags/GetTagsApi.yaml'

  /profile/me:
    $ref: './schemas/profile/GetMyProfileApi.yaml'
  /profile/header:
    $ref: './schemas/profile/GetProfileHeaderApi.yaml'

  /notifications/last:
    $ref: './schemas/notifications/GetLastNotificationsApi.yaml'
  /notifications:
    $ref: './schemas/notifications/GetNotificationsApi.yaml'
