name: "Lint Check"
description: "Runs lint checks using Gradle."
runs:
  using: "composite"
  steps:
    - name: Setup Testcontainers Cloud Client
      uses: atomicjar/testcontainers-cloud-setup-action@v1
      with:
        token: ${{ secrets.TC_CLOUD_TOKEN }}

    - name: Run lint checks
      run: |
        echo "Lint started"
        chmod +x ./gradlew
        ./gradlew checkstyleMain checkstyleTest --project-dir core
        echo "Lint completed"
      shell: bash

    - name: Upload Checkstyle Report
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: CheckstyleReport
        path: '**/build/reports/checkstyle/main.html'
