spring:
  datasource:
    url: jdbc:postgresql://84.201.168.8:5432/${INTERNSHIP_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.staziss-tech.ru/realms/internship
      client:
        provider:
          keycloak:
            issuer-uri: https://auth.staziss-tech.ru/realms/internship
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: users-app
            client-secret: BpD82qIQTGRARjrZLjx6FLeDXrBUrHYk
            scope:
              - openid
              - microprofile-jwt
              - profile
server:
  port: 8080