spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/${INTERNSHIP_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jooq:
    sql-dialect: postgres

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  codec:
    max-in-memory-size: 500KB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.staziss-tech.ru/realms/internship
      client:
        provider:
          keycloak:
            issuer-uri: https://auth.staziss-tech.ru/realms/internship
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: users-app
            client-secret: password
            scope:
              - openid
              - microprofile-jwt
              - profile

  kafka:
    bootstrap-servers: 127.0.0.1:9095
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      ack-mode: MANUAL_IMMEDIATE

  mail:
    host: smtp.gmail.com
    port: 587
    username: zdraviymalish@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

amazonProperties:
  bucketName: internship-hits
  endpointUrl: https://storage.yandexcloud.net

keycloak:
  internship:
    uri: https://auth.staziss-tech.ru
    realm: internship
    client-id: server-app
    client-secret: ${SERVER_APP_KEYCLOAK_SECRET}

exporter:
  logs:
    internship:
      source-topic: "raw.public.logs"
      group-id: "exporter-logs-internship"
    new:
      source-topic: "raw.public.logs_new"
      group-id: "exporter-logs-new"
  cdc:
    log_reactions:
      source-topic: "raw.public.log_reactions"
      group-id: "exporter-log_reactions"
    notification:
      source-topic: "raw.public.notification"
      group-id: "exporter-notification"

client:
  uri: https://internship.staziss-tech.ru
