name: Release

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Tag version for the release'
        required: true

env:
  APP_VERSION: ${{ github.event.inputs.app_version }}
  INTERNSHIP_DATABASE: ${{ secrets.INTERNSHIP_DATABASE }}
  POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
  POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  updateOpenapi:
    runs-on: self-hosted
    if: |
      ${{ github.event_name == 'push' &&
      github.event.head_commit.modified && 
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.modified, 'public/openapi/**') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker images
        run: ./deploy-swagger.sh

  updateDatabase:
    runs-on: ubuntu-latest
    needs:
      - updateOpenapi
    if: |
      ${{ github.event_name == 'push' &&
      github.event.head_commit.modified && 
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.modified, 'migrations/**') }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Liquibase Update
        uses: liquibase-github-actions/update@v4.29.1
        with:
          changelogFile: 'migration/changelog/root-changelog.yml'
          url: ${{ secrets.DATABASE_URL }}
          username: ${{ secrets.DATABASE_USERNAME }}
          password: ${{ secrets.DATABASE_PASSWORD }}

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - updateDatabase
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare docker
        uses: ./.github/actions/prepare-docker
        with:
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
          username: ${{ secrets.CI_REGISTRY_USER }}

      - name: Build Docker images
        env:
          CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}
        run: docker-compose build internship-app

      - name: Tag Docker images
        run: |
          docker tag ${{ secrets.CI_REGISTRY_IMAGE }}/internship-app:$APP_VERSION ${{ secrets.CI_REGISTRY_IMAGE }}/internship-app:latest

      - name: Push Docker images
        run: |
          docker push -a ${{ secrets.CI_REGISTRY_IMAGE }}/internship-app

      - name: Display build completion date
        run: echo "Build completed on $(date)"

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.APP_VERSION }}
          release_name: Release ${{ env.APP_VERSION }}
          body: "New release of the application"
          draft: false
          prerelease: false

  deploy:
    runs-on: self-hosted
    needs: release
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy Docker Image
        run: ./deploy.sh
