name: Lint and test

on: [ push, pull_request ]
env:
  INTERNSHIP_DATABASE: ${{ secrets.INTERNSHIP_DATABASE }}
  POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
  POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ru-central1
  SERVER_APP_KEYCLOAK_SECRET: ${{ secrets.SERVER_APP_KEYCLOAK_SECRET }}
  TC_CLOUD_TOKEN: ${{ secrets.TC_CLOUD_TOKEN }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare repository
        uses: ./.github/actions/prepare-repo

      - name: Run Lint Check
        uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare repository
        uses: ./.github/actions/prepare-repo

      - name: Run Test Check
        uses: ./.github/actions/test
