name: Lint and test

on: [ push, pull_request ]
env:
  INTERNSHIP_DATABASE: ${{ secrets.DATABASE_URL }}
  POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
  POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare repository
        uses: ./.github/actions/prepare-repo

      - name: Run Lint Check
        uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare repository
        uses: ./.github/actions/prepare-repo

      - name: Run Test Check
        uses: ./.github/actions/test
